### ISSUE TITLE
apps/dbs that are unprovisioned should say so on the deprovision tab

### ISSUE THREAD

**Issue by mixonic** [aptible/dashboard.aptible.com#116]

**Comment by bantic** [comment]
As of https://github.com/aptible/sweetness/pull/264 an app's status will be 'pending' when it has never been deployed.

**Comment by bantic** [comment]
@sandersonet Just wanted to run this by you.
The "deprovision" tab shows this, even for a never-been-deployed app:

![image](https://cloud.githubusercontent.com/assets/2023/6352530/5711d6ee-bc11-11e4-91c8-899a78948c84.png)

I've changed it so a never-deployed app's deprovision tab would show this:

![image](https://cloud.githubusercontent.com/assets/2023/6352570/97d79998-bc11-11e4-9232-d6aa3a9219d9.png)

Does that make sense? I'm thinking that even though you couldn't technically deprovision an app if it's never been provisioned a user may still want to delete it.

**Comment by sandersonet** [comment]
@bantic I thought never-deployed apps will show the deploy steps without any navigation?

On that note, I do agree we should allow a non-deployed app to be deprovisioned, but rather than still including the deprovision nav button, we could just add a small link to the deploy steps UI.

**Comment by bantic** [comment]
@sandersonet Cool, that makes sense. @mixonic and I had talked it over before and thought it might be confusing for a user if the UI nav changes depending on app state (tabs become visible after an app has been deployed) — we thought it would be more natural for the content of the tab to change rather than the tab itself to appear/disappear. I'm not sure if we ran this by you beforehand.

I think we *had* all decided to include the "deploy" and "activity" tabs.

Let's sync on this at some point today.

**Comment by sandersonet** [comment]
I think there are at least a couple of different scenarios to address here:

1) An app has been newly created and never deployed
2) An app has been created and deployed, but a subsequent deployment has removed all of the services

For scenario 1, the user should have a clear goal: deploy this app.   I think the existing deploy steps UI (without nav tabs) works great for this scenario.  We should also expose the ability to destroy the un-provisioned app with a single click.  I think just a small 'Destroy ${app.handle}' link at the bottom would work fine.

For scenario 2, I think you're right in that we should show all tabs (though maybe not domains?)  The app will still have relevant activity and should require verification in order to deprovision.  The services tab can show the deploy steps.

**Comment by mixonic** [comment]
I've got the:

> small 'Destroy ${app.handle}' link at the bottom would work fine.

part of this in https://github.com/aptible/diesel.aptible.com/pull/144

**Comment by sandersonet** [comment]
Pending apps don't show the deprovision tab, I think we can close this.
