### ISSUE TITLE
Migrate off Divshot

### ISSUE THREAD

**Issue by chasballew** [aptible/dashboard.aptible.com#286]
We've had a series of availability issues with Divshot over the past 2 months, and their responsiveness and transparency are not acceptable.

**Comment by fancyremarker** [comment]
I'll start by investigating what it would take to have an S3/CloudFront-based deploy. The biggest challenge is:

* [ ] Wildcard routing (@mixonic pointed out https://github.com/Kerry350/ember-deploy-s3-index#using-history-location but it has yet to be determined whether this will work with locations, rather than hash fragments)

Other issues (@mixonic, @skylar et al: feel free to add)

* [ ] Accept-Encoding: gzip
* [ ] Correct 304 responses for dynamic content and far-future expiry for static assets

We could deploy on Aptible as a fallback, but running a static site on a dynamic app server is not optimal.

**Comment by wmadden** [comment]
Deployment to a static hosting bucket on S3 is [fairly straightforward](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) as long as you know that `Alias Target` doesn't mean what it says and that the bucket has to have the exact same name as the subdomain in Route53.

It's possible to route wildcard requests to a single HTML page using the bucket's Redirection Rules ([stackoverflow](http://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html)).

**Comment by fancyremarker** [comment]
Thanks @wmadden! @mixonic: does the hash fragment redirect work with Ember's router?

**Comment by wmadden** [comment]
@fancyremarker the URLs in that article aren't hash fragments, they're actual paths. Hash fragments will work without any redirect rules or complicated setup.

E.g. if you have a bucket set up to serve some `index.html` at the domain `example.com`, `http://example.com/#/a/b/c` will go to `index.html` with the hash fragment `#/a/b/c`.

The complication is when you want `http://example.com/a/b/c` (as you'd have with pushstate routes which don't use hash fragments) to route to `index.html`.

**Comment by sandersonet** [comment]
Fixed by #335
