### ISSUE TITLE
Environment creation needs to define sweetness_stack

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#326]
Update: `sweetness_stack` will be defined manually for production accounts, and automatically for development accounts (in API).  The only code change required here is to trigger a custom event for 'Production Stack Created' whenever a user creates a production environment.  We'll also need to update customer.io to deliver a ticket to Ops to manually define the `sweetness_stack`.

---

`sweetness_stack` needs to be set on user-created environments.  I'm not sure on the best way to do this, or how we want to determine it.  I'm creating the ticket here, but ultimately I think the changes will live in aptible/api.aptible.com.  Here are some possible scenarios:

For development environments, we can do one of the following: 

1. We can leave it like it is and allow API to assign `ENV['DEFAULT_SWEETNESS_STACK']` as the environment's `sweetness_stack`
2. We can update API to use the `sweetness_stack` of any existing environments for that organization

For production environments, we can use the `sweetness_stack` from one of the organizations existing production stacks.  This could leave a customer open to getting into a bad state if they create a new environment before they have their existing production environment provisioned.  Perhaps we should block the creation of production environments until they have at least one that is `activated: true`.

Thoughts @fancyremarker ?

**Comment by fancyremarker** [comment]
My gut says that, at least to start, we should set `{ activated: false, sweetness_stack: nil }` on user-created production (i.e., PHI-ready) environments. For development environments, I think we can continue to use `DEFAULT_SWEETNESS_STACK`, and mark the account activated.

The reason is that some customers will want their PHI-ready environments to be separated from each other (i.e., on separate Sweetness stacks), while other customers will want their PHI-ready environments to live in the same stack.

So, to accommodate both use cases, I think we should leave the stack unset and fire an event that triggers an Ops ticket. In the future, once we have more data and a better sense for how and why customers choose to put their PHI-ready environments on the same or different stacks, we can give them UI to make that decision themselves.
