### ISSUE TITLE
Expose container_memory_limit_mb from UI

### ISSUE THREAD

**Issue by blakepettersson** [aptible/dashboard.aptible.com#516]
Add ability to set the `container_memory_limit_mb` directly from the UI. Maybe we should have some kind of slider to set this on a service level?

**Comment by fancyremarker** [comment]
:+1: I think that makes sense. The options should probably be limited to: 256 MB, 512 MB, 1 GB, 2 GB, 4 GB, 8 GB.

**Comment by sandersonet** [comment]
@fancyremarker Do we want to expose this for both DB and app containers?

**Comment by fancyremarker** [comment]
@sandersonet Yes, I think we'd want it for both, at least eventually. One catch is that updating the `container_memory_limit_mb` _won't_ immediately change the memory limit for live app or database. As of right now, the customer would need to run an `aptible restart` (for an app) or ask us to restart (for a database) in order for the change to take effect. There are a couple ways to improve this experience going forward:

* In Sweetness, either (a) add a `ResizeService` operation, or (b) allow `RestartApp` and `RestartDatabase` to take `container_memory_limit_mb` as an argument. These operations would be the only way to update the value of `container_memory_limit_mb`. In other words, it would not be directly updatable. This has the advantage that it's least confusing.
* In Dashboard, we could list the current containers and their memory limits under each service. A customer would _still_ need to restart their app in this scenario. This has the advantage that, once our billing summary reflects container sizing, we could make it easier for customers to tweak app/database footprints, see how their bill would change, and then actually restart their apps/databases in order to effect the change.

**Comment by blakepettersson** [comment]
@fancyremarker regarding what needs to be done in Sweetness - couldn't resizing a container be considered a `ScaleService` operation? In a way, the only real difference is that they are scaling the size of the container rather than scaling the number of containers.

**Comment by fancyremarker** [comment]
@blakepettersson: Yes, I agree with you. I think using `ScaleService` makes good sense here, instead of adding a `ResizeService` operation.

**Comment by blakepettersson** [comment]
Done!
